apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: test-app
spec:
  exporter:
    endpoint: http://otel-collector-collector.tracing.svc.cluster.local:4318
  env:
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on    
  python:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp_proto_http
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'

